apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-service
spec:
  template:
    spec:
      containers:
      - env:
        - name: TARGET
          value: v2 ## Change this or Image to get a new revision
        image: knativesamples/helloworld
        ports:
        - containerPort: 8080

        
  traffic:
   ## Update ABOVE and below to create a NEW knative revision.
    - latestRevision: true
      percent: 100 ## change to 20% to give 80% to old revision
      tag: green # change to "blue" to tag new revision

    ## Uncomment below to have old revision receive 80% of the traffic
    # - latestRevision: false
    #   percent: 80
    #   revisionName: serverless-service-00001
    #   tag: green
