apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: serverless-service
  namespace: serverless-demo
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/updateTimestamp: "2024-11-26T21:59:50Z"
        client.knative.dev/user-image: knativesamples/helloworld
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: TARGET
          value: v1
        - name: FROM
          value: examples
        image: knativesamples/helloworld
        name: ""
        ports:
        - containerPort: 8080
        resources: {}
status: {}
